// Generated by gencpp from file rvss_workshop/nextPose.msg
// DO NOT EDIT!


#ifndef RVSS_WORKSHOP_MESSAGE_NEXTPOSE_H
#define RVSS_WORKSHOP_MESSAGE_NEXTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rvss_workshop
{
template <class ContainerAllocator>
struct nextPose_
{
  typedef nextPose_<ContainerAllocator> Type;

  nextPose_()
    : nextPose()  {
    }
  nextPose_(const ContainerAllocator& _alloc)
    : nextPose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _nextPose_type;
  _nextPose_type nextPose;




  typedef boost::shared_ptr< ::rvss_workshop::nextPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvss_workshop::nextPose_<ContainerAllocator> const> ConstPtr;

}; // struct nextPose_

typedef ::rvss_workshop::nextPose_<std::allocator<void> > nextPose;

typedef boost::shared_ptr< ::rvss_workshop::nextPose > nextPosePtr;
typedef boost::shared_ptr< ::rvss_workshop::nextPose const> nextPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvss_workshop::nextPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvss_workshop::nextPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvss_workshop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'rvss_workshop': ['/home/monty/RVSS_ws/src/rvss_workshop/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::nextPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::nextPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::nextPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::nextPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::nextPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::nextPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvss_workshop::nextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "472aa9e9259455af5554754a873ea739";
  }

  static const char* value(const ::rvss_workshop::nextPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x472aa9e9259455afULL;
  static const uint64_t static_value2 = 0x5554754a873ea739ULL;
};

template<class ContainerAllocator>
struct DataType< ::rvss_workshop::nextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvss_workshop/nextPose";
  }

  static const char* value(const ::rvss_workshop::nextPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvss_workshop::nextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] nextPose\n\
";
  }

  static const char* value(const ::rvss_workshop::nextPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvss_workshop::nextPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nextPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nextPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvss_workshop::nextPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvss_workshop::nextPose_<ContainerAllocator>& v)
  {
    s << indent << "nextPose[]" << std::endl;
    for (size_t i = 0; i < v.nextPose.size(); ++i)
    {
      s << indent << "  nextPose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.nextPose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVSS_WORKSHOP_MESSAGE_NEXTPOSE_H
