// Generated by gencpp from file rvss_workshop/objDataArray.msg
// DO NOT EDIT!


#ifndef RVSS_WORKSHOP_MESSAGE_OBJDATAARRAY_H
#define RVSS_WORKSHOP_MESSAGE_OBJDATAARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rvss_workshop/objMsg.h>

namespace rvss_workshop
{
template <class ContainerAllocator>
struct objDataArray_
{
  typedef objDataArray_<ContainerAllocator> Type;

  objDataArray_()
    : header()
    , objects()  {
    }
  objDataArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rvss_workshop::objMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rvss_workshop::objMsg_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;




  typedef boost::shared_ptr< ::rvss_workshop::objDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvss_workshop::objDataArray_<ContainerAllocator> const> ConstPtr;

}; // struct objDataArray_

typedef ::rvss_workshop::objDataArray_<std::allocator<void> > objDataArray;

typedef boost::shared_ptr< ::rvss_workshop::objDataArray > objDataArrayPtr;
typedef boost::shared_ptr< ::rvss_workshop::objDataArray const> objDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvss_workshop::objDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvss_workshop::objDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvss_workshop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'rvss_workshop': ['/home/monty/RVSS_ws/src/rvss_workshop/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::objDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::objDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::objDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::objDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::objDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::objDataArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvss_workshop::objDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fb4a2149a0d8c8d308c11de8ad29ad3";
  }

  static const char* value(const ::rvss_workshop::objDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fb4a2149a0d8c8dULL;
  static const uint64_t static_value2 = 0x308c11de8ad29ad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rvss_workshop::objDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvss_workshop/objDataArray";
  }

  static const char* value(const ::rvss_workshop::objDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvss_workshop::objDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
objMsg[] objects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: rvss_workshop/objMsg\n\
Header header\n\
float32 Zrobot\n\
float32 Xrobot\n\
uint8 label\n\
float32[] covariance\n\
";
  }

  static const char* value(const ::rvss_workshop::objDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvss_workshop::objDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvss_workshop::objDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvss_workshop::objDataArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rvss_workshop::objMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVSS_WORKSHOP_MESSAGE_OBJDATAARRAY_H
