// Generated by gencpp from file rvss_workshop/objMsg.msg
// DO NOT EDIT!


#ifndef RVSS_WORKSHOP_MESSAGE_OBJMSG_H
#define RVSS_WORKSHOP_MESSAGE_OBJMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rvss_workshop
{
template <class ContainerAllocator>
struct objMsg_
{
  typedef objMsg_<ContainerAllocator> Type;

  objMsg_()
    : header()
    , Zrobot(0.0)
    , Xrobot(0.0)
    , label(0)
    , covariance()  {
    }
  objMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Zrobot(0.0)
    , Xrobot(0.0)
    , label(0)
    , covariance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _Zrobot_type;
  _Zrobot_type Zrobot;

   typedef float _Xrobot_type;
  _Xrobot_type Xrobot;

   typedef uint8_t _label_type;
  _label_type label;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _covariance_type;
  _covariance_type covariance;




  typedef boost::shared_ptr< ::rvss_workshop::objMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvss_workshop::objMsg_<ContainerAllocator> const> ConstPtr;

}; // struct objMsg_

typedef ::rvss_workshop::objMsg_<std::allocator<void> > objMsg;

typedef boost::shared_ptr< ::rvss_workshop::objMsg > objMsgPtr;
typedef boost::shared_ptr< ::rvss_workshop::objMsg const> objMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvss_workshop::objMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvss_workshop::objMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvss_workshop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'rvss_workshop': ['/home/monty/RVSS_ws/src/rvss_workshop/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::objMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::objMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::objMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::objMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::objMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::objMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvss_workshop::objMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92039726cacaf0739b94657d27987f60";
  }

  static const char* value(const ::rvss_workshop::objMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92039726cacaf073ULL;
  static const uint64_t static_value2 = 0x9b94657d27987f60ULL;
};

template<class ContainerAllocator>
struct DataType< ::rvss_workshop::objMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvss_workshop/objMsg";
  }

  static const char* value(const ::rvss_workshop::objMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvss_workshop::objMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 Zrobot\n\
float32 Xrobot\n\
uint8 label\n\
float32[] covariance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rvss_workshop::objMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvss_workshop::objMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Zrobot);
      stream.next(m.Xrobot);
      stream.next(m.label);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvss_workshop::objMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvss_workshop::objMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Zrobot: ";
    Printer<float>::stream(s, indent + "  ", v.Zrobot);
    s << indent << "Xrobot: ";
    Printer<float>::stream(s, indent + "  ", v.Xrobot);
    s << indent << "label: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.label);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVSS_WORKSHOP_MESSAGE_OBJMSG_H
