// Generated by gencpp from file rvss_workshop/reachedNextPose.msg
// DO NOT EDIT!


#ifndef RVSS_WORKSHOP_MESSAGE_REACHEDNEXTPOSE_H
#define RVSS_WORKSHOP_MESSAGE_REACHEDNEXTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rvss_workshop
{
template <class ContainerAllocator>
struct reachedNextPose_
{
  typedef reachedNextPose_<ContainerAllocator> Type;

  reachedNextPose_()
    : reachedNextPose(0)  {
    }
  reachedNextPose_(const ContainerAllocator& _alloc)
    : reachedNextPose(0)  {
  (void)_alloc;
    }



   typedef uint8_t _reachedNextPose_type;
  _reachedNextPose_type reachedNextPose;




  typedef boost::shared_ptr< ::rvss_workshop::reachedNextPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rvss_workshop::reachedNextPose_<ContainerAllocator> const> ConstPtr;

}; // struct reachedNextPose_

typedef ::rvss_workshop::reachedNextPose_<std::allocator<void> > reachedNextPose;

typedef boost::shared_ptr< ::rvss_workshop::reachedNextPose > reachedNextPosePtr;
typedef boost::shared_ptr< ::rvss_workshop::reachedNextPose const> reachedNextPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rvss_workshop::reachedNextPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rvss_workshop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'rvss_workshop': ['/home/monty/RVSS_ws/src/rvss_workshop/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rvss_workshop::reachedNextPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rvss_workshop::reachedNextPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rvss_workshop::reachedNextPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "599100cb215b4875f186eebbd5850cec";
  }

  static const char* value(const ::rvss_workshop::reachedNextPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x599100cb215b4875ULL;
  static const uint64_t static_value2 = 0xf186eebbd5850cecULL;
};

template<class ContainerAllocator>
struct DataType< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rvss_workshop/reachedNextPose";
  }

  static const char* value(const ::rvss_workshop::reachedNextPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 reachedNextPose\n\
";
  }

  static const char* value(const ::rvss_workshop::reachedNextPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reachedNextPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reachedNextPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rvss_workshop::reachedNextPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rvss_workshop::reachedNextPose_<ContainerAllocator>& v)
  {
    s << indent << "reachedNextPose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reachedNextPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVSS_WORKSHOP_MESSAGE_REACHEDNEXTPOSE_H
